spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9000/movieland
    username: user
    password: user

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate.default_schema: postgres.postgres.public
    show-sql: true
